import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'page_module.dart';

extension MaterialAppExtension on MaterialApp {
  GetMaterialApp modularize({
    required List<PageModule> pages,
    SmartManagement smartManagement = SmartManagement.full,
    ThemeMode themeMode = ThemeMode.system,
    Locale? fallbackLocale,
    TextDirection? textDirection,
    Map<LogicalKeySet, Intent>? shortcuts,
    CustomTransition? customTransition,
    Translations? translations,
    Map<String, Map<String, String>>? translationsKeys,
    VoidCallback? onInit,
    VoidCallback? onDispose,
    VoidCallback? onReady,
    ValueChanged<Routing?>? routingCallback,
    Transition? defaultTransition,
    bool? opaqueRoute,
    bool? enableLog,
    LogWriterCallback? logWriterCallback,
    bool? popGesture,
    Bindings? initialBinding,
    Duration? transitionDuration,
    bool? defaultGlobalState,
    PageModule? unknownRoute,
  }) {
    final getPages = pages.map((page) => page.page).toList();
    return GetMaterialApp.router(
      key: key,
      title: title,
      scaffoldMessengerKey: scaffoldMessengerKey,
      builder: builder,
      highContrastTheme: highContrastTheme,
      highContrastDarkTheme: highContrastDarkTheme,
      actions: actions,
      onGenerateTitle: onGenerateTitle,
      color: color,
      theme: theme,
      darkTheme: darkTheme,
      localeResolutionCallback: localeResolutionCallback,
      localizationsDelegates: localizationsDelegates,
      localeListResolutionCallback: localeListResolutionCallback,
      locale: locale,
      scrollBehavior: scrollBehavior,
      supportedLocales: supportedLocales,
      navigatorObservers: navigatorObservers ?? const <NavigatorObserver>[],
      debugShowMaterialGrid: debugShowMaterialGrid,
      showPerformanceOverlay: showPerformanceOverlay,
      checkerboardRasterCacheImages: checkerboardRasterCacheImages,
      checkerboardOffscreenLayers: checkerboardOffscreenLayers,
      showSemanticsDebugger: showSemanticsDebugger,
      debugShowCheckedModeBanner: debugShowCheckedModeBanner,
      smartManagement: smartManagement,
      themeMode: themeMode,
      fallbackLocale: fallbackLocale,
      textDirection: textDirection,
      shortcuts: shortcuts,
      customTransition: customTransition,
      translationsKeys: translationsKeys,
      translations: translations,
      onInit: onInit,
      onReady: onReady,
      onDispose: onDispose,
      routingCallback: routingCallback,
      defaultTransition: defaultTransition,
      getPages: getPages,
      opaqueRoute: opaqueRoute,
      enableLog: enableLog,
      logWriterCallback: logWriterCallback,
      popGesture: popGesture,
      transitionDuration: transitionDuration,
      defaultGlobalState: defaultGlobalState,
      initialBinding: initialBinding,
      unknownRoute: unknownRoute?.page,
      routerDelegate: routerDelegate,
      backButtonDispatcher: backButtonDispatcher,
      routeInformationParser: routeInformationParser,
      routeInformationProvider: routeInformationProvider,
    );
  }
}

extension CupertinoAppExtension on CupertinoApp {
  GetCupertinoApp modularize({
    required List<PageModule> pages,
    SmartManagement smartManagement = SmartManagement.full,
    ThemeMode themeMode = ThemeMode.system,
    Locale? fallbackLocale,
    TextDirection? textDirection,
    Map<LogicalKeySet, Intent>? shortcuts,
    CustomTransition? customTransition,
    Translations? translations,
    Map<String, Map<String, String>>? translationsKeys,
    VoidCallback? onInit,
    VoidCallback? onDispose,
    VoidCallback? onReady,
    ValueChanged<Routing?>? routingCallback,
    Transition? defaultTransition,
    bool? opaqueRoute,
    bool? enableLog,
    LogWriterCallback? logWriterCallback,
    bool? popGesture,
    Bindings? initialBinding,
    Duration? transitionDuration,
    bool? defaultGlobalState,
    PageModule? unknownRoute,
    ThemeData? highContrastTheme,
    ThemeData? highContrastDarkTheme,
  }) {
    final getPages = pages.map((page) => page.page).toList();
    return GetCupertinoApp.router(
      key: key,
      title: title,
      highContrastTheme: highContrastTheme,
      highContrastDarkTheme: highContrastDarkTheme,
      builder: builder,
      actions: actions,
      onGenerateTitle: onGenerateTitle,
      color: color,
      theme: theme,
      localeResolutionCallback: localeResolutionCallback,
      localizationsDelegates: localizationsDelegates,
      localeListResolutionCallback: localeListResolutionCallback,
      locale: locale,
      supportedLocales: supportedLocales,
      showPerformanceOverlay: showPerformanceOverlay,
      checkerboardRasterCacheImages: checkerboardRasterCacheImages,
      checkerboardOffscreenLayers: checkerboardOffscreenLayers,
      showSemanticsDebugger: showSemanticsDebugger,
      debugShowCheckedModeBanner: debugShowCheckedModeBanner,
      smartManagement: smartManagement,
      fallbackLocale: fallbackLocale,
      textDirection: textDirection,
      shortcuts: shortcuts,
      customTransition: customTransition,
      translationsKeys: translationsKeys,
      translations: translations,
      onInit: onInit,
      onReady: onReady,
      onDispose: onDispose,
      routingCallback: routingCallback,
      defaultTransition: defaultTransition,
      getPages: getPages,
      opaqueRoute: opaqueRoute,
      enableLog: enableLog,
      logWriterCallback: logWriterCallback,
      popGesture: popGesture,
      transitionDuration: transitionDuration,
      defaultGlobalState: defaultGlobalState,
      initialBinding: initialBinding,
      unknownRoute: unknownRoute?.page,
      routerDelegate: routerDelegate,
      backButtonDispatcher: backButtonDispatcher,
      routeInformationParser: routeInformationParser,
      routeInformationProvider: routeInformationProvider,
    );
  }
}
